"""Pydantic models for request/response schemas."""

from app.models.ai import (
    AnswerRequest,
    AnswerResponse,
    CoverLetterPDFRequest,
    CoverLetterRequest,
    CoverLetterResponse,
    MatchAnalysisRequest,
    MatchAnalysisResponse,
    OutreachRequest,
    OutreachResponse,
)
from app.models.autofill import (
    AutofillDataResponse,
    PersonalData,
    ResumeData,
)
from app.models.feedback import (
    FeedbackCategory,
    FeedbackRequest,
    FeedbackResponse,
)
from app.models.job import (
    JobCreateRequest,
    JobListItem,
    JobListResponse,
    JobNotesUpdateRequest,
    JobResponse,
    JobStatus,
    JobStatusUpdateRequest,
    JobUpdateRequest,
)
from app.models.subscriptions import (
    CheckoutRequest,
    CheckoutResponse,
    MockCancelRequest,
    PortalResponse,
    SubscriptionTier,
)
from app.models.privacy import (
    AIGeneratedContentInfo,
    CancelDeleteResponse,
    ConfirmDeleteRequest,
    ConfirmDeleteResponse,
    DataSummary,
    DeleteReason,
    DeleteRequestRequest,
    DeleteRequestResponse,
    JobStatusBreakdown,
    JobStorageInfo,
    ProfileStorageInfo,
    ResumeStorageInfo,
    UsageHistoryStorageInfo,
    UsageOperationBreakdown,
)
from app.models.usage import (
    UsageByType,
    UsageEventItem,
    UsageHistoryResponse,
    UsageResponse,
)

__all__ = [
    "AIGeneratedContentInfo",
    "AnswerRequest",
    "AnswerResponse",
    "AutofillDataResponse",
    "CancelDeleteResponse",
    "FeedbackCategory",
    "FeedbackRequest",
    "FeedbackResponse",
    "CheckoutRequest",
    "CheckoutResponse",
    "ConfirmDeleteRequest",
    "ConfirmDeleteResponse",
    "CoverLetterPDFRequest",
    "CoverLetterRequest",
    "CoverLetterResponse",
    "DataSummary",
    "DeleteReason",
    "DeleteRequestRequest",
    "DeleteRequestResponse",
    "JobCreateRequest",
    "JobListItem",
    "JobListResponse",
    "JobNotesUpdateRequest",
    "JobResponse",
    "JobStatus",
    "JobStatusBreakdown",
    "JobStatusUpdateRequest",
    "JobStorageInfo",
    "JobUpdateRequest",
    "MatchAnalysisRequest",
    "MatchAnalysisResponse",
    "MockCancelRequest",
    "OutreachRequest",
    "OutreachResponse",
    "PersonalData",
    "PortalResponse",
    "ProfileStorageInfo",
    "ResumeData",
    "ResumeStorageInfo",
    "SubscriptionTier",
    "UsageByType",
    "UsageEventItem",
    "UsageHistoryResponse",
    "UsageHistoryStorageInfo",
    "UsageOperationBreakdown",
    "UsageResponse",
]
